// Tool for local documentation QA. Requires Playwright and installed Chrome.
const fs = require('fs');
const path = require('path');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname, '..');
(async()=>{
 fs.mkdirSync(path.join(root,'artifacts/screenshots'),{recursive:true});
 const browser = await chromium.launch({channel:'chrome', headless:true});
 const page = await browser.newPage({viewport:{width:1200,height:900},deviceScaleFactor:1});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8001/');
 await page.getByRole('button',{name:'Рассчитать и сохранить'}).click();
 await page.getByText('HTTP 201',{exact:true}).waitFor();
 if(!(await page.locator('#score').innerText()).includes('0.185'))throw Error('Wrong UI score');
 await page.screenshot({path:path.join(root,'artifacts/screenshots/dashboard.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 await page.setViewportSize({width:900,height:900});
 await page.goto('http://127.0.0.1:8001/docs');
 await page.locator('.opblock').first().waitFor({timeout:60000});
 await page.addStyleTag({content:'.swagger-ui pre, .swagger-ui .microlight {font-size:16px !important;} .swagger-ui .response-col_status {font-size:16px !important;}'});
 await page.screenshot({path:path.join(root,'artifacts/screenshots/swagger.png'),fullPage:true});
 const operation=page.locator('#operations-Прогнозы-predict_predict_post');
 await operation.locator('.opblock-summary').click();
 await operation.getByRole('button',{name:'Try it out'}).click();
 const input=operation.locator('textarea');
 await input.fill(fs.readFileSync(path.join(root,'examples/low.json'),'utf8'));
 await operation.getByRole('button',{name:'Execute',exact:true}).click();
 await operation.locator('.responses-inner .response-col_status').filter({hasText:'201'}).first().waitFor();
 await page.waitForFunction(()=>document.querySelector('#operations-Прогнозы-predict_predict_post .live-responses-table')?.innerText.includes('201'));
 await operation.locator('.live-responses-table').screenshot({path:path.join(root,'artifacts/screenshots/predict-201.png')});
 await input.fill(fs.readFileSync(path.join(root,'examples/invalid.json'),'utf8'));
 await operation.getByRole('button',{name:'Execute',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#operations-Прогнозы-predict_predict_post .live-responses-table')?.innerText.includes('422'));
 await operation.locator('.live-responses-table').screenshot({path:path.join(root,'artifacts/screenshots/validation-422.png')});
 await operation.locator('.opblock-summary').click();
 const missing=page.locator('#operations-Прогнозы-prediction_predictions__request_id__get');
 await missing.locator('.opblock-summary').click();
 await missing.getByRole('button',{name:'Try it out'}).click();
 await missing.locator('input[type=text]').fill('00000000-0000-0000-0000-000000000000');
 await missing.getByRole('button',{name:'Execute',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#operations-Прогнозы-prediction_predictions__request_id__get .live-responses-table')?.innerText.includes('404'));
 await missing.locator('.live-responses-table').screenshot({path:path.join(root,'artifacts/screenshots/not-found-404.png')});
 if(errors.length) throw Error(errors.join('\n'));
 console.log('Browser UI, mobile layout, Swagger 201/422/404: PASS');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
